apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    app: zdslabs
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volumedocontainer
          name: primeiro-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: nginx-container
      image: nginx:stable
      volumeMounts:
        - mountPath: /volumedocontainer
          name: primeiro-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/volume-primeiro
        type: DirectoryOrCreate
  ports:
    - containerPort: 80
