apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zdslabs-statefulset
spec:
  selector:
    matchLabels:
      app: zdslabs
  serviceName: svc-zdslabs
  replicas: 1
  template:
    metadata:
      labels:
        app: zdslabs
    spec:
      containers:
      - name: zdslabs-container
        image: zdsdocker/zds-labs_web:1.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: sassao
          mountPath: /tmp
      volumes:
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc