apiVersion: apps/v1
kind: Deployment
metadata:
  name: zdslabs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zdslabs
  template:
    metadata:
      name: zdslabs
      labels:
        app: zdslabs
    spec:
      containers:
      - name: zdslabs-container
        image: zdsdocker/zds-labs_web:1.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
